import { boundedContextChunks } from "../chat-policy.js";import{buildGeneralPrompt,buildRagPrompt,buildSafetyPrompt}from"../prompts.js";import{extractJsonObject}from"../rag-security.js";import{loadVisibleContextChunks}from"../rag/context.js";
/** @param {string} text */
export function responseTag(text){return ["[RAG]","[DRIFT]","[NO INFO]"].find(tag=>text.trimStart().startsWith(tag))??null;}
/** @param {string} text @param {any[]} chunks */
export function ensureResponseTag(text,chunks){return responseTag(text)?text:`${chunks.length?"[DRIFT]":"[NO INFO]"}\n${text.trimStart()}`;}
/** @param {string} text */
export function removeResponseTag(text){const tag=responseTag(text);return tag?text.trimStart().slice(tag.length).replace(/^[\r\n ]+/,""):text;}
/** @param {any} data */export function normalizeSafety(data){const value=data&&typeof data==="object"&&!Array.isArray(data)?data:{};const label=["SAFE","REVIEW","SUSPICIOUS"].includes(String(value.label??"").toUpperCase())?String(value.label).toUpperCase():"SAFE";const confidence=Math.max(0,Math.min(1,Number(value.confidence)||0));return{label,confidence:Number(confidence.toFixed(3)),summary:String(value.summary??"No clear manipulation patterns detected"),signals:Array.isArray(value.signals)?value.signals.map(String).filter(Boolean).slice(0,6):[],evidence:Array.isArray(value.evidence)?value.evidence.map(String).filter(Boolean).slice(0,4):[]};}
/** @param {import("fastify").FastifyInstance} app @param {Record<string,any>} model @param {string} question */export async function analyzeSafety(app,model,question){try{return normalizeSafety(extractJsonObject(await app.emmaGeneration.generate(model,[{role:"user",content:buildSafetyPrompt(question)}])));}catch{return{...normalizeSafety(null),summary:"Safety analysis unavailable"};}}
/** @param {import("fastify").FastifyInstance} app @param {Array<{role:string,content:string}>} messages @param {Record<string,any>} model @param {{id:number,role:string}} user */export async function prepareChat(app,messages,model,user){const question=messages.at(-1)?.content.trim()??"";const chunks=boundedContextChunks(await loadVisibleContextChunks(app,user,model),app.emmaConfig.maxContextChars);const prompt=chunks.length?buildRagPrompt(question,chunks):buildGeneralPrompt(question);return{question,chunks,aiMessages:[...messages.slice(0,-1),{role:"user",content:prompt}],safety:await analyzeSafety(app,model,question)};}
