import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join, parse } from "node:path";
import { buildInconsistencyPrompt } from "../prompts.js";
import { extractJsonObject } from "../rag-security.js";

/** @param {string} filesDir */ export function loadConflictsIndex(filesDir) { return readObject(join(filesDir, "conflicts_index.json")); }
/** @param {unknown} record @param {string} [status] */ export function conflictsResponse(record, status="unchecked") { const value=record&&typeof record==="object"&&!Array.isArray(record)?/** @type {Record<string,any>} */(record):null; const matches=Array.isArray(value?.matches)?value.matches:[]; return {has_any:matches.length>0,matches,status:value?.status??status,...(value?.checked_at?{checked_at:value.checked_at}:{})}; }
/** @param {string} filesDir @param {string} stem @param {Array<Record<string,any>>} matches */ export function saveConflicts(filesDir,stem,matches){if(!existsSync(join(filesDir,`${stem}.txt`)))return;const index=loadConflictsIndex(filesDir);index[stem]={matches,status:"checked",checked_at:new Date().toISOString()};writeJson(join(filesDir,"conflicts_index.json"),index);}
/** @param {string} filesDir */ export function pruneOrphanedConflicts(filesDir){const valid=new Set(existsSync(filesDir)?readdirSync(filesDir).filter(n=>n.endsWith(".txt")).map(n=>parse(n).name):[]);const index=loadConflictsIndex(filesDir);for(const [stem,record] of Object.entries(index)){if(!valid.has(stem)){delete index[stem];continue;}if(record&&typeof record==="object"&&Array.isArray(record.matches))record.matches=record.matches.filter((/** @type {Record<string,any>} */ m)=>m&&typeof m==="object"&&(!m.candidate_stem||valid.has(String(m.candidate_stem))));}writeJson(join(filesDir,"conflicts_index.json"),index);return index;}
/** @param {string} chunksPath */ export function excerptFromChunks(chunksPath){const data=readObject(chunksPath);const chunks=Array.isArray(data.chunks)?data.chunks:[];return chunks.map((/** @type {Record<string,any>} */ c)=>String(c?.text??"").trim()).filter(Boolean).join("\n\n---\n\n").slice(0,5000);}
/** Compare candidates through the injected model boundary. @param {{name:string,stem:string,scope:string,chunksPath:string}} source @param {Array<{name:string,stem:string,scope:string,chunksPath:string}>} candidates @param {Record<string,any>} model @param {(model:Record<string,any>,messages:Array<{role:string,content:string}>)=>Promise<string>} generate */
export async function compareDocumentInconsistencies(source,candidates,model,generate){const sourceExcerpt=excerptFromChunks(source.chunksPath);const matches=[];for(const candidate of candidates){const candidateExcerpt=excerptFromChunks(candidate.chunksPath);if(!sourceExcerpt||!candidateExcerpt)continue;const raw=await generate(model,[{role:"user",content:buildInconsistencyPrompt(source.name,sourceExcerpt,candidate.name,candidate.scope,candidateExcerpt)}]);const parsed=extractJsonObject(raw);if(parsed?.has_inconsistencies!==true||!Array.isArray(parsed.items))continue;const items=parsed.items.filter(keepItem);if(items.length)matches.push({candidate_name:candidate.name,candidate_stem:candidate.stem,candidate_scope:candidate.scope,summary:String(parsed.summary??""),items});}return matches;}
/** @param {any} item */ function keepItem(item){return item&&typeof item==="object"&&String(item.topic??"").trim()&&String(item.new_claim??"").trim()&&String(item.existing_claim??"").trim()&&["low","medium","high"].includes(String(item.severity??"").toLowerCase());}
/** @param {string} path */ function readObject(path){try{const data=JSON.parse(readFileSync(path,"utf8"));return data&&typeof data==="object"&&!Array.isArray(data)?data:{};}catch{return{};}}
/** @param {string} path @param {unknown} value */ function writeJson(path,value){writeFileSync(path,`${JSON.stringify(value,null,2)}\n`,"utf8");}
